omaha/base/security/p224_ec.c

Fixing the error #78 :
"_left shift count >= width of type_"
in 16-bit architectures.

Fix 16bit arch compatibility

---

doc/DeveloperSetupGuide.md

In order to run the unit tests, the current version requires creating a registry key value at `HKEY_LOCAL_MACHINE\SOFTWARE\OmahaCompanyName\UpdateDev`, not `HKEY_LOCAL_MACHINE\SOFTWARE\Google\UpdateDev`. This PR updates the documentation to reflect this.
Further, I have added a note to the documentation in an attempt to help the reader avoid a common pitfall when creating registry keys for 32 bit processes on 64 bit Windows.

Update documentation on running unit tests

---

README.md

The documentation is very good, but leaves a lot of things to the reader to figure out. I wrote a [tutorial](https://fman.io/blog/google-omaha-tutorial/) in the hope of making Omaha more accessible. This PR adds a link to the tutorial to the README.

Mention third-party tutorial in README

---

doc/DeveloperSetupGuide.md

A dependency on 'protobuf/implicit_weak_message.cc' was added on PR 441e20999427f0af9f1aabb35ac98682bdd7c49f. This file only exists on protobuf version 3.6.0 and higher and user older versions (which used to work before) now causes a build break.
This pull request updates the guide to specify the new requirement.

DeveloperSetupGuide.md protobuf version required.

---

omaha/main.scons

`NTDDI_VERSION` was defined in CPPDEFINES as `DNTDDI_VERSION`. The D prefix would be valid for CPPFLAGS, but not here.
Fix for #144

Define NTDDI_VERSION correctly

---

doc/DeveloperSetupGuide.md
omaha/main.scons
omaha/precompile/precompile.h

Add workaround for latest VS 2017 15.9 updates which break when `winioctl.h` is included due to an unmatched `#pragma warning(push)`.
Fix mismatched values of WINVER and NTDDI_VERSION (see #145 ).
Update the value to Win7, because:
* The code won't compile due to `base/synchronized.cc` which needs `CREATE_EVENT_MANUAL_RESET` introduced in Vista
* Vista support lifecycle had ended, so it makes sense to move to Win 7.

Update WINVER to Windows 7 value.

---

omaha/common/xml_parser.cc

ElementHandler is created on heap and never released. Wrapping it with scoped_ptr fixes the issue.

Fix a leaked pointer in XmlParser::VisitElement

---

.gitignore
doc/DeveloperSetupGuide.md
omaha/base/string.h
omaha/common/xml_parser.cc
omaha/hammer.bat
omaha/main.scons
omaha/omaha_version_utils.py
omaha/precompile/precompile.h
omaha/site_scons/site_tools/atlmfc_vc16_0.py
omaha/site_scons/site_tools/omaha_builders.py
omaha/site_scons/site_tools/windows_vc16_0.py
omaha/third_party/smartany/scoped_any.h
omaha/tools/MsiTagger/msi_tag_tool.cc

This may require additional work to sort through necessary prior commits, like the Scons3 work.
The included new python files in
omaha/site_scons/site_tools/*_vc16_*.py
are almost entirely derivative of prior versions of those files, so the copyrights are copied unchanged.
Additional breakpad fixes are necessary, but might be resolved with more warnings disabled.
Mostly this is a bunch of casting changes, but it will not build as-is without other work.  Please feel free to ignore it entirely, but I thought there might be useful bits for you to pillage if we're working toward the same thing.

Support VS2019 builds

---

omaha/main.scons
omaha/ui/splash_screen.cc

An ICE occurs when building with 16.1.0 in service\service_main.h
https://developercommunity.visualstudio.com/content/problem/579068/internal-compiler-error-1610-compiler-file-dagent.html

Fix for ICE with 16.1.0 toolchain

---

.clang-format

Proposing to add `.clang-format` file set to Chromium style.
Omaha code mostly follows Chromium and Google C++ style guide already.
This should ensure that any new code is formatted consistently if the contributors use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) tool before check ins.

Add .clang-format file to the root.

---

omaha/net/winhttp.cc

WinHttpCreateUrl requires buffer size.
Original code set buffer size parameter to zero.

Fix to pass buffer size.

---

omaha/core/core.cc
omaha/core/core.h
omaha/core/scheduler.cc
omaha/core/scheduler.h
omaha/core/scheduler_unittest.cc
omaha/testing/build.scons

The issue is related to #177. The `scoped_ptr::reset method` would first destroy an object and
then set the contained ptr to null. The `std::unique_ptr`, however, does it in the reverse order.
The destructor of `QueueTimer` waits on a critical section that allows it
to wait for pending timer callbacks during teardown.
Therefore, the `Scheduler::~Scheduler` will wait on `update_timer.reset(...)`
in one thread, while trying to access `update_timer` value in another thread.
With this change, the pointer passed as the context of the timer callback will
be use instead of trying to access the contained `unique_ptr` value.

Fix a race in the Scheduler dtor after unique_ptr change

---

omaha/ui/owner_draw_title_bar.cc

`CRgnHandle rgn` leaks the region created by the `CreateRectRgnIndirect` method in each OnPaint method call.
This means, that if the download takes a while and we exhaust the GDI object limit, then `CreateRectRgnIndirect` will fail and bootstrapper would crash.
I'd guess it's a bad copy-paste from other places where `CreateRectRgnIndirect`.
Changing `rgn` to be of type `CRgn` ensures that `DeleteObject` is called when the object goes out of scope.

Fix leak of the region GDI handle

---

omaha/common/config_manager.cc
omaha/common/config_manager.h
omaha/core/build.scons
omaha/core/core.cc
omaha/core/core.h
omaha/core/core_launcher.cc
omaha/core/core_launcher.h
omaha/core/core_unittest.cc
omaha/core/winmain.cc
omaha/testing/build.scons

Extract code that is needed for GoogleUpdateCore.exe to launch GoogleUpdate.exe /c. 
This change reduces unnecessary linkage in the Core executable.
Size on disk before:
```
1,170,024 GoogleUpdateSetup.exe
344,408 GoogleUpdateCore.exe
```
after:
```
1,158,760 GoogleUpdateSetup.exe   ( - 11,264 /  -1% )
213,848 GoogleUpdateCore.exe ( - 130,560  / - 38%)
```

Reduce the size on disk of GoogleUpdateCore.exe

---

omaha/base/process.cc
omaha/goopdate/ondemand.h
omaha/third_party/smartany/scoped_any.h

- Fix bool to HANDLE conversion in base/process.cc
- Fix missing header in goopdate/ondemand.h 
- Fix wrong template type in smart_any.h
Note: Omaha still doesn't build with `/permissive-` mode in 16.4 due to a bug in atlenc.h.

Fix build errors with VS 16.4

---

omaha/main.scons
omaha/net/simple_request.cc
omaha/net/simple_request.h

- ERROR_WINHTTP_RESEND_REQUEST is compare to HRESULT from this error. This comparison is never satisfied and this change fixes it.
- Add "max resend" count to avoid resending infinitely.
- Add `/WX` flag for linking to treat linker warnings as errors.
- Change some linker options to use uppercase - doesn't seen matter in scons but MSDN states that these are case-sensitive

Fix comparison of HRESULT with ERROR_WINHTTP_RESEND_REQUEST

---

omaha/net/simple_request.cc
omaha/net/winhttp_adapter.cc
omaha/net/winhttp_adapter.h
omaha/net/winhttp_adapter_unittest.cc

Log secure status flag for WININET_E_DECODING_FAILED - on Win 7 this error can happen when you change time and the cert trust cannot be verified. We can make this error more actionable by logging WinHTTP status.
The unforunate fact is that `WININET_E_DECODING_FAILED`  is equivalent to `HRESULT_FROM_WIN32(ERROR_INTERNET_DECODING_FAILED)` as well as `HRESULT(ERROR_WINHTTP_SECURE_FAILURE)` and you can't tell the two.

Log secure status flag for WININET_E_DECODING_FAILED

---

omaha/core/scheduler_unittest.cc

The SchedulerTest.DeleteSoonBeforeCallbackExpires seems flaky. The 10ms difference between the scheduler interval and the timeout sometimes isn't enough. Increase the delta to 50ms.

Increase the delta in DeleteSoonBeforeCallbackExpires to 50ms

---

README.md

Most people will find it useful to get a quick overview of how Omaha works before jumping into the Developer Setup Guide. This change helps them find the link.

Move link to unofficial tutorial up in README

---

doc/DeveloperSetupGuide.md
omaha/base/build.scons
omaha/main.scons

Disable warnings C5204 and C5205 that break ATL headers.
Update Developer Setup Guide.

Fix building with VS 2019 16.5

---

omaha/third_party/smartany/smart_any_fwd.h

As noticed in the Chromium code, we can disable the legacy feature by passing COINIT_DISABLE_OLE1DDE to CoInitializeEx.

Initialize COM with COINIT_DISABLE_OLE1DDE 

---

omaha/base/app_util_unittest.cc
omaha/base/system_info.cc
omaha/base/utils.h
omaha/common/goopdate_utils.cc
omaha/crashhandler/crash_analyzer_checks.cc
omaha/crashhandler/crash_analyzer_debugee_test.cc
omaha/goopdate/cred_dialog.cc
omaha/net/network_config.cc
omaha/net/proxy_auth.cc
omaha/net/winhttp_vtable.cc
omaha/tools/goopdump/process_commandline.cc

When loading system DLLs, use `LoadLibraryEx` with `LOAD_LIBRARY_SEARCH_SYSTEM32` flag to scope to loading dlls from %windir%\System32 directory only.

Use LOAD_LIBRARY_SEARCH_SYSTEM32 when loading system libs

---

omaha/common/scheduled_task_utils.cc
omaha/common/scheduled_task_utils.h
omaha/core/core.cc

The behavior of `scheduled_task_utils::GetExitCodeGoopdateTaskUA` is slightly different on Windows 7 which causes AreScheduledTasksHealthy to return false, even when things are fine.
The impact on Win7 is that, since we incorrectly determine that the scheduled tasks are unhealthy, we decide that we `Core::ShouldRunForever()` and we fallback to the infinite restart Scheduler/SystemMonitor approach. I'm not familiar with the implications of that, but I assume it's worse than using the scheduled tasks. Also, this behavior causes the test `CoreUtilsTest.AreScheduledTasksHealthy` to fail on Win7. With this patch, the test passes on Win7.
The subtle difference is:
- on Win10, if the UA task has never run before, then its "last task result" is initialized to 0x41303 SCHED_S_TASK_HAS_NOT_RUN. …

Fix Core::AreScheduledTasksHealthy on Windows 7

---

omaha/common/ping_test.cc

The bug here is that `PingTest.BuildOmahaPing` copies a shell exe into the Google Update exe path, then neglects to delete it when it's done. 
This leads to strange interactions with other tests which interact with the shell exe, like the `ShouldInstall_*` tests in `setup_unittest.cc`. Most of those tests start off by copying the build output into the Google Update directory, including the shell exe. But, they copy with `replace_existing_file=false`, so they don't overwrite if there's a file already there.
In particular, `SetupRegistryProtectedUserTest.ShouldInstall_NewerVersion` expects to have the current version of the shell exe available. There's also a different setup test which deletes the shell exe: `SetupRegistryProtectedUserTest.ShouldInstall_NewerVersionShellMissing`. So …

PingTest.BuildOmahaPing: clean up shell exe after test

---

omaha/test/build.scons

This part of omaha/test/build.scons throws errors during the build. It complains that SignTool.exe does not support dual-signing for MSIs.
python C:\Omaha\src\omaha/tools/retry.py 10 5 "C:\Omaha\depot_tools\win_toolchain\vs_files\c3f20336a802feafb047f13730eed8b7d7fedb62\win_sdk\bin\10.0.19041.0\x86/signtool.exe" sign /v /f "C:\Omaha\src\omaha/data/Sha2OmahaTestCert.pfx" /p "888" /tr "http://timestamp.digicert.com" /td "SHA256" /as /fd "SHA256" "scons-out\dbg-win\obj\test\enterprise_test_foo_v1.0.101.0.msi"
SignTool Error: Multiple signature support is not implemented for this filetype.
SignTool Error: An error occurred while attempting to sign: scons-out\dbg-win\obj\test\enterprise_test_foo_v1.0.101.0.msi
We don't actually use this behavior downstream on Edge but I thought I'd send a PR …

Single-sign test MSIs

---

omaha/enterprise/installer/custom_actions/msi_tag_extractor_test.cc

These tests assume that `omaha_unittest.exe` will always be run directly from a folder named `staging/`. Although this is true by default, it's not a guarantee. In some CI environments, build output is packaged up and copied into a directory with a different name e.g. `test_bin/`. That breaks these tests since now the path `../staging/unittest_support/tagged_msi` no longer exists.
The fix is to reference the folder directly like `./unittest_support`, instead of `../staging/unittest_support`.
Repro:
```powershell
./omaha/hammer.bat MODE=dbg-win --build_server
./omaha/scons-out/dbg-win/staging/omaha_unittest.exe --gtest_filter=MsiTagExtractorTest* --gtest_list_tests
./omaha/scons-out/dbg-win/staging/omaha_unittest.exe --gtest_filter=MsiTagExtractorTest*
mkdir ./tmp
cp -r …
```

MsiTagExtractorTest: direct path to unittest_support files 

---

omaha/common/experiment_labels.cc

If running as machine and the response from server contains experiment labels, the client tries to delete experiment_labels value from "HKLM\\Software\\Google\\Update\\ClientStateMedium\\{XXXX-XXXX-XXXX-XXX-XXXXX}" registry key without checking whether the key exists. Under some circumstances, it doesn't exist thus failing the assert and resulting in a crash. (e.g. a new install from GoogleUpdateSetup.exe)

Verify registry key/value exists: fixes updater crash in debug mode

---

omaha/goopdate/build.scons
omaha/goopdate/com_register_shell.cc

Found while doing a pass of ComRegisterShell:
1. security_64.lib and crypt.lib are unused, and can be removed
2. basictypes.h and path.h are unused, and can be removed
This passes our build and all tests downstream on Edge.

Lighten deps of ComRegisterShell

---

omaha/setup/setup_files_unittest.cc

When the files are named differently than the Google defaults, the ordering changes.
This commit changes the test to ignore ordering changes.
Fixes: #321

Make *.Install_NotOverInstall test ignore file order

---

omaha/base/utils_unittest.cc

ReadEntireFile: allow for either LF or CRLF line endings

---

omaha/goopdate/app.h
omaha/goopdate/app_manager.cc
omaha/goopdate/app_manager.h
omaha/goopdate/app_manager_unittest.cc

Update `AppManager::ReadPersistentData` to also load the persisted `usagestats` consent state from the registry into the `App` object. This allows the `App` object to know its usage stats consent state elsewhere in the update process, e.g. while building pings.
App manager unit tests are updated to cover the behavior. Build and tests all pass downstream on Edge.

Load usage stats consent from the registry into the App object

---

omaha/base/error.h
omaha/net/bits_request.cc

BITS is a downloader designed with download queues in mind which can be manipulated by different users. Part of the design is to take into consideration that if a user logs-off then a job that was started by the user should be put back in queue until the user logs back in. This design does not work well for Omaha system-level installs which impersonate users to access proxy information but do not have the intention to suspend jobs during logoff.
Working around the behavior:
Changing how impersonation scoping works on those requests would be risky at this point. So, we're putting a surgical fix for this specific case. If a bits job ever reaches transferring state and "goes back" to queued, then we log a warning and let the download use a fallback instead of blocking on a sleep loop. …

Avoid BITS getting stuck in queued state during user logoff

---

omaha/common/omaha_customization_unittest.cc

Exclude Google-specific unit test checks when GOOGLE_UPDATE_BUILD not defined

---

omaha/base/logging.cc

`LogWriter::Unregister` calls `Logging::RegisterWriter` when it should call `Logging::UnregisterWriter`

Fix LogWriter Unregister
